# Generated by Django 2.1.5 on 2020-02-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200227_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ecommerce.Product'),
        ),
    ]
