# Generated by Django 2.1.5 on 2020-02-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200228_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Others', max_length=45),
        ),
    ]
